### ISSUE TITLE
[BUG] Issue when runnning multipe pools (Bun)

### ISSUE THREAD

**Issue by calumk** [poolifier/poolifier-web-worker#39]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I am getting an error when i try to run a FixedThreadPool with more than **1**

## Working
```js
// a fixed worker_threads pool -> 1
const pooly = new FixedThreadPool(1, new URL('_worker.js', import.meta.url), {
    errorHandler: (e) => console.error(e),
    onlineHandler: () => console.info('worker is online')
})
```

## Not Working
```js
// a fixed worker_threads pool -> 2
const pooly = new FixedThreadPool(2, new URL('_worker.js', import.meta.url), {
    errorHandler: (e) => console.error(e),
    onlineHandler: () => console.info('worker is online')
})
```

Error message - relates to use of transformers.js - but only happens when i trigger multiple poolls

<img width="859" alt="image" src="https://github.com/poolifier/poolifier-web-worker/assets/1183991/f86f44f9-f290-4fc7-8470-6aaa180c4bdb">

---

> [!Note]
> This worked perfectly before using node - I am porting to bun, issue could be transformers.js related but could also be something triggered here?

**Comment by calumk** [comment]
@xenova - I have an issue here, using your new branch - running it on its own seems fine, but running it in poolifer seems to cause an issue

**Comment by jerome-benoit** [comment]
Reference: https://github.com/poolifier/poolifier-web-worker/commit/746bbd71a3243634aa313eec3e0a6de1a747cf5d
